name: Jekyll-MDBootstrap
baseurl: ""
url: "https://snake0053.github.io/Jekyll-MDBootstrap/"
# Build settings
markdown: kramdown

social:
  Website: https://snake0053.xyz/
  Twitter: https://twitter.com/snake0053
  YouTube: /#
  GitHub: https://github.com/snake0053/Jekyll-MDBootstrap

nav:
  - title: Home
    url: /
  - title: item 1
    dropdown:
      - title: item 1
        url: /#
      - title: item 2
        url: /#
      - title: item 3
        url: /#
      - title: item 4
        url: /#
